
trigger:
  branches:
    include:
    - main

# Enable debug logging
variables:
  system.debug: true  # This will turn on detailed logging

pool:
  name: AzurePipeline  # Replace with the name of your self-hosted agent pool

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Specify the Node.js version you need

    - task: CmdLine@2
      displayName: 'Install dependencies'
      inputs:
        script: |
          npm install
    - task: CmdLine@2
      displayName: 'Package the function app'
      inputs:
        script: |
          powershell Compress-Archive -Path * -DestinationPath functionapp.zip

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'functionapp.zip'
        artifactName: 'drop'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    steps:
    - task: CmdLine@2
      displayName: 'Run Tests'
      inputs:
        script: |
          npm test

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'  # 🔹 Refers to the published artifact
        downloadPath: 'C:\Users\Butt\CICD\_work\1'  # Downloads to a temporary location

    - script: dir C:\Users\Butt\CICD\_work\1\drop
      displayName: 'Check downloaded artifacts'  # Debugging step

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'AzureServiceConnection1'  # Use your Azure Service Connection name
        appName: 'AzurePipelineFunctionApp'  # Replace with your actual Function App name
        package: 'C:\Users\Butt\CICD\_work\1\drop\functionapp.zip'


